-- users / announcements 新增列。SQLite 不能重复执行 ADD COLUMN。
-- houduan 启动时会检查列名，缺哪列补哪列，一般不必手工执行本文件。

ALTER TABLE users ADD COLUMN username TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN avatar TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN phone TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN bind_email TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN email_verified_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN email_bind_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN email_status INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN is_distributor INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN is_agent INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN commission_mode INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN wallet_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN can_authorize_agent INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN parent_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN distributor_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN relation_path TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN member_status INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN banned_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN ban_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN invite_code TEXT NOT NULL DEFAULT '';

ALTER TABLE announcements ADD COLUMN notice_type TEXT NOT NULL DEFAULT 'notice';
ALTER TABLE announcements ADD COLUMN starts_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE announcements ADD COLUMN ends_at INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users(username) WHERE username <> '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_bind_email ON users(bind_email) WHERE bind_email <> '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_invite ON users(invite_code) WHERE invite_code <> '';
